INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('100 Grand',true,false,true,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('3 Musketeers',true,false,false,false,true,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Air Heads',false,true,false,false,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Almond Joy',true,false,false,true,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Baby Ruth',true,false,true,true,true,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Boston Baked Beans',false,false,false,true,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Candy Corn',false,false,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Caramel Apple Pops',false,true,true,false,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Charleston Chew',true,false,false,false,true,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Chewey Lemonhead Fruit Mix',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Chiclets',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Dots',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Dum Dums',false,true,false,false,false,true,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Fruit Chews',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Fun Dip',false,true,false,false,false,true,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Gobstopper',false,true,false,false,false,true,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Haribo Gold Bears',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Haribo Happy Cola',false,false,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Haribo Sour Bears',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Haribo Twin Snakes',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Hersheys Kisses',true,false,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Hersheys Krackel',true,false,false,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Hersheys Milk Chocolate',true,false,false,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Hersheys Special Dark',true,false,false,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Jawbusters',false,true,false,false,false,true,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Junior Mints',true,false,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Kit Kat',true,false,false,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Laffy Taffy',false,true,false,false,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Lemonhead',false,true,false,false,false,true,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Lifesavers Gummies',false,true,false,false,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Peanut butter M&Ms',true,false,false,true,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('M&Ms',true,false,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Mike & Ike',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Milk Duds',true,false,true,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Milky Way',true,false,true,false,true,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Milky Way Midnight',true,false,true,false,true,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Milky Way Simply Caramel',true,false,true,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Mounds',true,false,false,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Mr Good Bar',true,false,false,true,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Nerds',false,true,false,false,false,true,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Nestle Butterfinger',true,false,false,true,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Nestle Crunch',true,false,false,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Nik L Nip',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Now & Later',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Payday',false,false,false,true,true,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Peanut M&Ms',true,false,false,true,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Pixie Sticks',false,false,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Pop Rocks',false,true,false,false,false,true,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Red vines',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Reeses Miniatures',true,false,false,true,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Reeses Peanut Butter cup',true,false,false,true,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Reeses pieces',true,false,false,true,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Ring Pop',false,true,false,false,false,true,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Rolo',true,false,true,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Root Beer Barrels',false,false,false,false,false,true,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Runts',false,true,false,false,false,true,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Sixlets',true,false,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Skittles',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Skittles Wildberry',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Smarties',true,false,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Snickers',true,false,true,true,true,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Sour Patch Kids',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Starburst',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Strawberry Bon Bons',false,true,false,false,false,true,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Sugar Babies',false,false,true,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Sugar Daddy',false,false,true,false,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Super Bubble',false,true,false,false,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Swedish Fish',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Tootsie Pop',true,true,false,false,false,true,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Tootsie Rolls',true,false,false,false,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Tootsie Roll Snack Bars',true,false,false,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Trolli Sour Bites',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Twix',true,false,true,false,false,false,true,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Twizzlers',false,true,false,false,false,false,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Warheads',false,true,false,false,false,true,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Welchs Fruit Snacks',false,true,false,false,false,false,false,true);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Werthers Original Caramel',false,false,true,false,false,true,false,false);
INSERT INTO candies(candyname,chocolate,fruit,caramel,nut,nougat,hard,bar,plural) VALUES ('Whoppers',true,false,false,false,false,false,false,true);